name: IA32 Tests

on: push

env:
  protoc_version: '3.x'

jobs:
  windows:
    name: "Deploy Github: Windows"
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: arduino/setup-protoc@v1
        with: { version: "${{ env.protoc_version }}", repo-token: "${{ github.token }}" }
      - uses: dart-lang/setup-dart@v1
        with:
          architecture: ia32
      - run: dart pub get
      - run: dart run grinder protobuf
      - run: dart run grinder pkg-standalone-windows-ia32
      - run: dart run grinder pkg-standalone-windows-x64
      - uses: actions/upload-artifact@v3
        with:
          path: build/*.zip